---
  # This failed (once only) with error:
  # TypeError: _execute_module() got an unexpected keyword argument 'wrap_async'
  #
  # But  sudo apt-get install python-pexpect says:
  # python-pexpect is already the newest version (4.0.1-1)
  #
  # so it's ok to ignore the fail (as long as that's the cause :/ )
  #
- name: Install source control for ansible
  pip:
    name: source_control
  become: true

- name: Install pexpect for ansible expect module
  apt:
    name: python-pexpect
    state: installed
    update_cache: yes
  become: true
  ignore_errors: yes
  no_log: true
  
- name: Install openssl for ansible
  pip:
    name: pyOpenSSL
  become: true

