---
- hosts: cftest.intersect.org.au
  tasks:
   - name: Install packages
     action: apt pkg={{item}} state=installed update_cache=yes
     with_items:
      - python-virtualenv
      - build-essential
      - openssh-server
      - apache2
      - gcc
      - gdal-bin
      - gettext
      - git-core
      - libapache2-mod-wsgi
      - libgeos-dev
      - libjpeg-dev
      - libpng-dev
      - libpq-dev
      - libproj-dev
      - libxml2-dev
      - libxslt-dev
      - openjdk-8-jre
      - patch
      - postgresql
      - postgis
      - postgresql-9.5-postgis-scripts
      - postgresql-contrib
      - python
      - python-dev
      - python-gdal
      - python-pycurl
      - python-imaging
      - python-pastescript
      - python-psycopg2
      - python-urlgrabber
      - python-virtualenv
      - tomcat7
      - unzip
      - zip
     become: true

   - name: Check if python-support is installed
     command: dpkg-query -W python-support 
     register: check_deb
     failed_when: check_deb.rc > 1
     changed_when: check_deb.rc == 1

   - name: Download python-support
     get_url:
       url: http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
       dest: /home/{{ ansible_env.USER }}/python-support_1.0.15_all.deb
     when: check_deb.rc == 1

   - name: Install python-support
     apt: deb="/home/{{ ansible_env.USER }}/python-support_1.0.15_all.deb"
     become: true
     when: check_deb.rc == 1
