---
- hosts: localhost
  tasks:

   - name: Install pexpect for ansible expect module
     apt:
       pkg: python-pexpect
       state: installed
       update_cache: yes
     become: true

   - name: Hack Ansible git
     # Workaround for Ansible git error when dest exists and is modified, and force=yes:
     # UnboundLocalError: local variable 'remote_head' referenced before assignment
     # See ansible issue #5504: https://github.com/ansible/ansible-modules-core/issues/5504
     #
     lineinfile:
       dest: /usr/lib/python2.7/dist-packages/ansible/modules/core/source_control/git.py
       regexp: '\s*result.update\(changed=True, .*msg=.Local modifications exist.\)'
       line: "                result.update(changed=True, msg='Local modifications exist')"
     become: true
