printf "ansible-playbook install_geonode.yml --extra-vars \"host=HOSTNAME tmp=TMPDIR home=GEONODE_HOME_DIR dbhome=DATABASE_HOME_DIR gsdata=GEOSERVER_DATA_DIR admin_email=EMAIL admin_pass=PASSWORD sitename=\'Site Name\' orgname=\'Organisation Name\' country=XX target_host=ACTUAL_HOST_NOT_ALIAS\" --step --start-at-task=\"FIRST_TASK\" \n"
printf "\n"
printf "ansible-playbook install_ssl.yml --extra-vars \"host=HOSTNAME home=GEONODE_HOME_DIR gsdata=GEOSERVER_DATA_DIR python_lib=PYTHON_LIB_PATH\" --step --start-at-task=\"FIRST_TASK\" \n"
printf "\n"
printf "ansible-playbook install_backup.yml --extra-vars \"host=HOSTNAME backup_exclude=\'{path1,path2}\' backup_from_dir=FROM_FOLDER backup_to_server=SERVER_NAME backup_to_dir=TO_FOLDER\" \n"
printf "\n"
printf "ansible-playbook remove_ssl.yml --extra-vars \"host=HOSTNAME home=GEONODE_HOME_DIR gsdata=GEOSERVER_DATA_DIR\" --step --start-at-task=\"FIRST_TASK\" \n"
