---
- include: install_geonode/1_packages_installation.yml
- include: install_geonode/2_geonode_setup.yml
- include: install_geonode/3_install_ssh_keys_for_postgres.yml
- include: install_geonode/4_create_geonode_db.yml
- include: install_geonode/5_change_user_access_policy.yml
- include: install_geonode/6_setup_httpd.yml
- include: install_geonode/7_copy_geonode_data.yml
- include: install_geonode/8_install_geoserver_application.yml
- include: install_geonode/9_geonode_configuration.yml

- hosts: '{{ host }}'
  tasks:
  - name: Test if site is available
    uri:
      url: http://{{ host }}

  - name: Completion message
    vars:
      msg: |
           Geonode installed on http://{{ host }}
           Now login to http://{{ host }}/geoserver as admin and change master password:
           Security > Passwords > Active master password provider > Change password
    debug:
      msg: "{{ msg.split('\n') }}"

  - name: Print master password if available
    debug:
      msg: "{{ masterpw.stdout }}"
    when: masterpw.stdout is defined
