---
- include: install_geonode/00_mv_tmp_to_big_disk.yml
- include: install_geonode/01_packages_installation.yml
- include: install_geonode/02_geonode_setup.yml
- include: install_geonode/03_install_ssh_keys_for_postgres.yml
- include: install_geonode/04_create_geonode_db.yml
- include: install_geonode/05_change_user_access_policy.yml
- include: install_geonode/06_setup_httpd.yml
- include: install_geonode/07_copy_geonode_data.yml
- include: install_geonode/08_install_geoserver_application.yml
- include: install_geonode/09_geonode_configuration.yml
- include: install_geonode/10_generate_ssl_csr.yml

- hosts: '{{ host }}'
  tasks:
  - name: Test if site is available
    uri:
      url: http://{{ host }}

  - name: Completion message
    vars:
      msg: |
           Geonode installed on http://{{ host }}
           Now login to http://{{ host }}/geoserver as admin and change master password:
           Security > Passwords > Active master password provider > Change password
    debug:
      msg: "{{ msg.split('\n') }}"

  - name: Print master password if available
    debug:
      msg: "{{ masterpw.stdout }}"
    when: masterpw.stdout is defined
