---
- hosts: {{ host }}
  tasks:
    - include: install_geonode/1_packages_installation.yml
    - include: install_geonode/2_geonode_setup.yml
    - include: install_geonode/3_install_ssh_keys_for_postgres.yml
    - include: install_geonode/4_create_geonode_db.yml
    - include: install_geonode/5_change_user_access_policy.yml
    - include: install_geonode/6_setup_httpd.yml
    - include: install_geonode/7_copy_geonode_data.yml
    - include: install_geonode/8_install_geoserver_application.yml
    - include: install_geonode/9_geonode_configuration.yml

    - debug: msg='Geonode installed. Geonode should now be running on http://{{ host }}.intersect.org.au'
    - debug: msg='Now login to Geonode as admin and configure example.com at Admin > Sites'
