---
- hosts: '{{ host }}'
  tasks:
   - name: Install local settings
     template:
       src: 09.1_local_settings.py.j2
       dest: '{{ home }}/geonode/geonode/local_settings.py'
     become: true

   - name: Upgrade beautifulsoup
     # To avoid bug when running /manage.py fixsitename
     # See https://bugs.launchpad.net/beautifulsoup/+bug/1603299
     pip:
       name: beautifulsoup4
       version: 4.5.1
     become: true

   - name: Fix sitename
     command: python '{{ home }}/geonode/manage.py' fixsitename
     