---
- hosts: '{{ host }}'
  tasks:
   - name: Create GeoNode Superuser
     # Will fail if superuser already exists. Ignore this and suppress error log.
     command: python '{{ home }}/geonode/manage.py' createsuperuser --noinput --username=admin --email='{{ admin_email }}'
     ignore_errors: yes
     no_log: true
