---
- hosts: '{{ host }}'
  tasks:
#   - name: Encrypt the site with Apache Secure Sockets Layer (SSL)
#     become: true

   - name: Install openssl for ansible
     pip:
       name: pyOpenSSL
     become: true

# The first step is to generate a DES key.:
# for CommonName use GeoNode domain name or ip address as specified in GeoNode's SITEURL
# genrsa superceded by genpkey. - https://linux.die.net/man/1/openssl

# openssl genpkey -des3 -out server.key 1024
openssl req -new -key server.key -out server.csr

   - name: Generate a private key
     openssl_privatekey:
       path: server.key
       size: 1024
       type: RSA
     become: true

   - name: Generate a certificate signing request
     openssl_csr:
       path: server.csr
       privatekey_path: server.key
       commonName: '{{ host }}'
       countryName: AU
       organizationName: '{{ orgname }}'
       emailAddress: '{{ admin_email }}'
     become: true
   
   
# generate new server.key without challenge password, or Apache will ask for password at startup
#mv server.key server.key.tmp
#openssl rsa -in server.key.tmp -out server.key
#
# generate certificate
#openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt






#     copy:
#       src: 9.1_local_settings.py
#       dest: '{{ home }}/geonode/geonode/local_settings.py'
