---
- hosts: '{{ host }}'
  tasks:
   - name: Add apache geonode config
     copy:
       src: 6_geonode.conf
       dest: /etc/apache2/sites-available/geonode.conf
     become: true
   
   - name:  Enable proxy_http
     apache2_module:
       state: present
       name: proxy_http
     become: true

   - name: Disable default apache site
     command: a2dissite 000-default
     become: true

   - name: Enable geonode apache site
     command: a2ensite geonode
     become: true

   - name: Create world-writable thumbs and layers directories
     file:
       path: /home/geonode/geonode/geonode/uploaded/{{item}}
       state: directory
       mode: a=rwx
     with_items: 
      - thumbs
      - layers
     become: true

   - name: Change owner of geonode home to geonode
     file:
       path: /home/geonode/geonode
       state: directory
       owner: geonode
       recurse: yes
     become: true

   - name: Change owner and group of static and uploaded directories
     file:
       path: /home/geonode/geonode/geonode/{{item}}
       state: directory
       owner: geonode
       group: www-data
     with_items:
      - static
      - uploaded
     become: true

   - name: Change owner and group of static_root directory
     file:
       path: /home/geonode/geonode/geonode/static_root
       state: directory
       owner: www-data
       group: www-data
     become: true
