---
- hosts: '{{ host }}'
  tasks:
   - name: Stop Tomcat
     service:
       name: tomcat7
       state: stopped
     become: true

   - name: Copy Geoserver war to Tomcat
     command: cp /home/geonode/geonode/downloaded/geoserver.war /var/lib/tomcat7/webapps/
     become: true

   - name: Restart Tomcat to deploy Geoserver
     service:
       name: tomcat7
       state: restarted
     become: true

   - name: Stop Tomcat again
     service:
       name: tomcat7
       state: stopped
     become: true

   - name: Increase JVM memory
     # In response to 'OutOfMemoryError: Java heap space error' on uploading large layer
     # See: http://docs.geonode.org/en/master/tutorials/advanced/geonode_production/adv_gsconfig/gsproduction.html#configuring-your-container-for-production
     lineinfile:
       dest: /etc/default/tomcat7
       regexp: '^\s*JAVA_OPTS\s*=.*$'
       line: 'JAVA_OPTS="-Djava.awt.headless=true -Xms2048m -Xmx2048M -XX:+UseConcMarkSweepGC"'
     become: true

   - name: Add GeoNode base url to geoserver config
     blockinfile:
       dest: /var/lib/tomcat7/webapps/geoserver/WEB-INF/web.xml
       marker: '<!-- {mark} ANSIBLE MANAGED BLOCK -->'
       insertafter: '</context-param>'
       block: |
         <context-param>
         <param-name>GEONODE_BASE_URL</param-name>
         <param-value>http://localhost/</param-value>
         </context-param>
     become: true

   - name: Set digest password encoding
     # To remove warning message: The default user/group service should use digest password encoding.
     lineinfile:
       dest: /var/lib/tomcat7/webapps/geoserver/data/security/usergroup/default/config.xml
       regexp: '\s*<passwordEncoderName>.*'
       line: '  <passwordEncoderName>digestPasswordEncoder</passwordEncoderName>'
     become: true

   - name: Restart Tomcat
     service:
       name: tomcat7
       state: restarted
     become: true

   - name: Remove masterpw.info file to remove security risk warning
     file:
       path: /var/lib/tomcat7/webapps/geoserver/data/security/masterpw.info
       state: absent
     become: true
