---
- hosts: '{{ host }}'
  tasks:
   - name: Create GeoNode Superuser
     command: python /home/geonode/geonode/manage.py createsuperuser --noinput --username=admin --email='{{ admin_email }}'
     ignore_errors: yes
     no_log: true
