---
- hosts: '{{ host }}'
  tasks:
   - name: Change superuser password
     # Separating this task from previous one (createsuperuser) allows playbook to be idempotent.
     # I.e. password can be changed on an existing superuser account.
     expect:
       command: python /home/geonode/geonode/manage.py changepassword admin
       responses:
         Password: '{{ admin_pass }}'
         Password (again): '{{ admin_pass }}'
