---
- include: 9.1_add_apache_geonode_config.yml
- include: 9.2_initialize_the_database.yml
- include: 9.3_create_geonode_superuser.yml
- include: 9.4_change_superuser_password.yml
- include: 9.5_restart_apache.yml
