---
- hosts: '{{ host }}'
  tasks:
   - include: 9.1_add_apache_geonode_config.yml
   - include: 9.2_initialize_the_database.yml
   - include: 9.3_create_geonode_superuser.yml
   - include: 9.4_restart_apache.yml
