---
- hosts: '{{ inventory_hostname }}'
  tasks:
   - name: Copy GeoNode data to be served by Apache
     expect:
       command: python '{{ home }}/geonode/manage.py' collectstatic
       responses:
         'Type .yes. to continue, or .no. to cancel:': 'yes'
     become: true

   - name: Restart Apache
     service:
       name: apache2
       state: restarted
     become: true
