---
- name: Test if site is available
  uri:
    url: http://{{ inventory_hostname }}

- name: Completion message
  vars:
    msg: |
         Geonode installed on http://{{ inventory_hostname }}
         Now login to http://{{ inventory_hostname }}/geoserver as admin and change master password:
         Security > Passwords > Active master password provider > Change password
  debug:
    msg: "{{ msg.split('\n') }}"

- name: Print master password if available
  debug:
    msg: "{{ masterpw.stdout }}"
  when: masterpw is defined