---
- name: Download GeoServer web archive
  shell: export PYTHONHTTPSVERIFY=0 && paver setup
  args:
    chdir: '{{ gnhome }}/geonode'
  become: true

- name: Stop Tomcat
  service:
    name: {{ tomcat }}
    state: stopped
  become: true

- name: Copy Geoserver war to Tomcat
  command: cp {{ gnhome }}/geonode/downloaded/geoserver-{{ geoserver_version }}.war /var/lib/{{ tomcat }}/webapps/geoserver.war
  become: true

- name: Force Tomcat Restart to deploy Geoserver
  service:
    name: {{ tomcat }}
    state: restarted
  become: true

- name: Stop Tomcat again
  service:
    name: {{ tomcat }}
    state: stopped
  become: true

- name: Increase JVM memory
  # In response to 'OutOfMemoryError: Java heap space error' on uploading large layer
  # See: http://docs.geonode.org/en/master/tutorials/advanced/geonode_production/adv_gsconfig/gsproduction.html#configuring-your-container-for-production
  # Further increased Xms and Xmx from 2048 to 4096, and added MaxPermSize=512m after out of memory error from WMS call 11/7/2017
  lineinfile:
    dest: /etc/default/{{ tomcat }}
    regexp: '^\s*JAVA_OPTS\s*=.*$'
    line: 'JAVA_OPTS="-Djava.awt.headless=true -Xms4096m -Xmx4096M -XX:MaxPermSize=512m -XX:+UseConcMarkSweepGC"'
  become: true

- name: Check geoserver data folder on data disk
  stat:
    path: '{{ gsdata }}'
  register: new_gsdata

- name: Move Geoserver data directory to data disk if not already there
  command: mv /var/lib/{{ tomcat }}/webapps/geoserver/data '{{ gsdata }}'
  become: true
  when: "new_gsdata.stat.exists == False and 'small_sysdisk' in group_names"

- name: Delete new empty Geoserver data directory if old one exists on data disk
  file:
    path: /var/lib/{{ tomcat }}/webapps/geoserver/data
    state: absent
  become: true
  when: "new_gsdata.stat.exists == True and 'small_sysdisk' in group_names"

- name: Check link to geoserver data folder
  stat:
    path: /var/lib/{{ tomcat }}/webapps/geoserver/data
  register: gsdatalink

- name: Link Geoserver data directory if not already done
  file:
    src: '{{ gsdata }}'
    path: /var/lib/{{ tomcat }}/webapps/geoserver/data
    state: link
  become: true
  when: "gsdatalink.stat.islnk is not defined or (gsdatalink.stat.islnk is defined and gsdatalink.stat.islnk == False) and 'small_sysdisk' in group_names"

- name: Add GeoNode base url to geoserver config
  blockinfile:
    dest: /var/lib/{{ tomcat }}/webapps/geoserver/WEB-INF/web.xml
    marker: '<!-- {mark} ANSIBLE install_geoserver_application MANAGED BLOCK -->'
    insertbefore: '<filter>'
    block: |
      <context-param>
      <param-name>GEONODE_BASE_URL</param-name>
      <param-value>http://localhost/</param-value>
      </context-param>
  become: true

- name: add Cross-Origin Resource Sharing (CORS) on geoserver
  blockinfile:
    dest: /var/lib/{{ tomcat }}/conf/web.xml
    insertbefore: </web-app>
    marker: '<!-- {mark} ANSIBLE install_geoserver_application MANAGED BLOCK -->'
    block: |
      <!-- The filter to allow Cross-Origin Resource Sharing (CORS) -->
      <filter>
        <filter-name>CorsFilter</filter-name>
        <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
      </filter>
      <!-- The mapping for the CORS Filter: url pattern is relative to context /geoserver -->
      <filter-mapping>
        <filter-name>CorsFilter</filter-name>
        <url-pattern>/*</url-pattern>
      </filter-mapping>
  become: true
  notify:
    - Restart Tomcat

- name: Set digest password encoding
  # To remove warning message: The default user/group service should use digest password encoding.
  lineinfile:
    dest: /var/lib/{{ tomcat }}/webapps/geoserver/data/security/usergroup/default/config.xml
    regexp: '\s*<passwordEncoderName>.*'
    line: '  <passwordEncoderName>digestPasswordEncoder</passwordEncoderName>'
  become: true
  notify:
    - Restart Tomcat

- name: Check for masterpw.info file
  stat:
    path: /var/lib/{{ tomcat }}/webapps/geoserver/data/security/masterpw.info
  register: masterpw_file

- name: Save Geoserver master password
  command: grep 'master password is' /var/lib/{{ tomcat }}/webapps/geoserver/data/security/masterpw.info
  register: masterpw
  when: masterpw_file.stat.exists == True

- debug:
    var: masterpw_file.stdout

- name: Remove masterpw.info file to remove security risk warning
  file:
    path: /var/lib/{{ tomcat }}/webapps/geoserver/data/security/masterpw.info
    state: absent
  become: true
