---
- name: Create geonode user
  user:
    name: geonode
    home: '{{ gnhome }}'
  become: true

- name: Clone geonode from repo
  git:
    clone: yes
    force: yes
    repo: '{{ geonode_repo_url }}'
    # version: '{{ geonode_version }}' # This got the wrong version, as shown in dev_config.yml
    dest: '{{ gnhome }}/geonode'
  become: true

- name: Delete old pyc file
  file:
    name: '{{ gnhome }}/geonode/geonode/client/admin.pyc'
    state: absent
  become: true

- name: Install geonode
  pip:
    name: '{{ gnhome }}/geonode'
  become: true

- name: Set system-wide environment variables
  blockinfile:
    path: /etc/environment
    block: |
      SITE_HOST_NAME={{ inventory_hostname }}
      SITENAME="{{ project }}"
      SITE_HOST_PORT={{ port }}
      DJANGO_SETTINGS_MODULE=geonode.settings
      AVATAR_DEFAULT_URL="http://localhost:{{ port }}/static/img/avatar.png"
  become: true
