---
- name: Install packages
#     action: apt pkg= state=installed update_cache=yes
  apt:
    name: '{{ item }}'
    state: installed
    # update_cache: yes - failed with error
  with_items:
   - python-virtualenv
   - build-essential
   - openssh-server
   - apache2
   - gcc
   - gdal-bin
   - gettext
   - git-core
   - libapache2-mod-wsgi
   - libgeos-dev
   - libjpeg-dev
   - libpng12-dev
   - libpq-dev
   - libproj-dev
   - libxml2-dev
   - libxslt1-dev
   - openjdk-8-jre
   - patch
   - postgresql
   - postgis
   - postgresql-9.5-postgis-scripts
   - postgresql-contrib
   - python
   - python-dev
   - python-gdal
   - python-pexpect
   - python-pycurl
   - python-imaging
   - python-pastescript
   - python-psycopg2
   - python-urlgrabber
   - python-virtualenv
   - tomcat8
   - unzip
   - zip
   - ncdu
  become: true

- name: Check if python-support is installed
  command: dpkg-query -W python-support
  register: check_deb
  failed_when: check_deb.rc > 1
  changed_when: check_deb.rc == 1

- name: Download python-support
  get_url:
    url: http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
    dest: "{{ ansible_env.HOME }}/python-support_1.0.15_all.deb"
  when: check_deb.rc == 1

- name: Install python-support
  apt: deb="{{ ansible_env.HOME }}/python-support_1.0.15_all.deb"
  become: true
  when: check_deb.rc == 1
