---

- include_tasks: mount_disk.yml

- name: Check tmp folder
  stat:
    path: /tmp
  register: tmp

- include_tasks: mv_tmp_to_big_disk.yml
  when: "tmp.stat.islnk is not defined or (tmp.stat.islnk is defined and tmp.stat.islnk == False) and 'small_sysdisk' in group_names"

################################################################
#
#                             IMPORTANT
#
# As a workaround to an open Ansible issue (#14468) the
# install_packages.yml playbook must be run using python3
# interpreter
#
# A test-python3 inventory file has been created for test target
#
# For other targets:
#   copy their inventory file into another (adding suffix -python3)
#   and add the python3 interpreter as shown in test-python3
#
# Then run:
#   ansible-playbook geonode.yml -i test-python3 --tags py3
#
################################################################

# Test if tomcat7 is installed
- name: Check if packages installed
  service:
    name: tomcat7
    state: stopped
  become: true
  ignore_errors: yes
  register: run_installed_package

- include_tasks: install_packages.yml
  tags:
    - py3

- name: Message to install packages
  vars:
    msg: |
         As a workaround for open Ansible issue #14468, please install the packages using the python3 interpreter.

         This command will just run tasks tagged py3 (in install_packages.yml):
           ansible-playbook geonode.yml -i testpy3 --tags py3
  debug:
    msg: "{{ msg.split('\n') }}"
  when: run_installed_package is defined and run_installed_package.failed

- meta: end_play
  when: run_installed_package is defined and run_installed_package.failed

- include_tasks: move_postgres.yml
  when: "'small_sysdisk' in group_names"

- include_tasks: geonode_setup.yml
- include_tasks: install_ssh_keys_for_postgres.yml

- include_tasks: create_geonode_db.yml
  remote_user: postgres

- include_tasks: change_user_access_policy.yml
- include_tasks: setup_httpd.yml
- include_tasks: copy_geonode_data.yml
- include_tasks: install_geoserver_application.yml
- include_tasks: geonode_configuration.yml
- include_tasks: generate_ssl_csr.yml
- include_tasks: admin_envt.yml
- include_tasks: completion.yml
