---

- include_tasks: move_postgres.yml

- include_tasks: install_geonode.yml

- include_tasks: create_geonode_db.yml

- include_tasks: setup_httpd.yml

- include_tasks: install_geoserver_application.yml
- include_tasks: config_geonode.yml
# - include_tasks: generate_ssl_csr.yml
# - include_tasks: install_admin_tools.yml
# - include_tasks: admin_envt.yml
- include_tasks: complete.yml
