---
- include: mv_tmp_to_big_disk.yml
  when: "'small_sysdisk' in group_names"

- include: install_packages.yml

- include: geonode_setup.yml

- include: setup_httpd.yml
- include: copy_geonode_data.yml
- include: install_geoserver_application.yml
- include: geonode_configuration.yml
- include: generate_ssl_csr.yml
- include: completion.yml
