---
- name: Save post-processed template
  template:
    src: citydata.j2
    dest: '{{ role_path }}/outputs/citydata.json'

- name: Delete any stack from a previous run
  cloudformation:
    stack_name: '{{ project }}-{{ envt | upper }}'
    region: '{{ aws_region }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    state: absent

- name: Create stack
  cloudformation:
    stack_name: '{{ project }}-{{ envt | upper }}'
    template_body: "{{ lookup('template', 'citydata.j2') }}"
    region: '{{ aws_region }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    state: present
  register: stack_result

- name: Delete stack if failed
  cloudformation:
    stack_name: '{{ project }}-{{ envt | upper }}'
    region: '{{ aws_region }}'
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    state: absent
  when: stack_result is failed

- name: print IP address(es)
  debug:
    msg: '{{ stack_result.stack_outputs }}'
