---
- name: Set siteurl to use http
  replace:
    dest: '{{ home }}/geonode/geonode/local_settings.py'
    regexp: '(^\s*SITEURL\s*=\s*.?)https:'
    replace: '\1http:'
  become: true
  notify:
    - Restart Apache
  
- name: Reset OGC server to use http and localhost
  replace:
    dest: '{{ home }}/geonode/geonode/local_settings.py'
    regexp: '(^\s*\047LOCATION\047\s*:\s*\047)https:\/\/[^\/]+/geoserver'
    replace: '\1http://localhost/geoserver'
  become: true
  notify:
    - Restart Apache

- name: Call gravatar with http
  lineinfile:
    dest: '{{ home }}/geonode/geonode/local_settings.py'
    line: 'AVATAR_GRAVATAR_SSL = True'
    state: absent
  become: true
  notify:
    - Restart Apache