---
- hosts: '{{ host }}'
  tasks:

   - name: Restart Apache
     service:
       name: apache2
       state: restarted
     become: true

   - name: Restart Tomcat
     service:
       name: tomcat7
       state: restarted
     become: true