---
- name: Install backup shell script
  template:
    src: backupRestoreGeonode.j2
    dest: ~/backupRestoreGeonode
    mode: 0700

- name: create filesystem for backup
  filesystem:
    dev: /dev/{{ backup_disk_volume }}
    fstype: ext4
    # force: yes # Only need this if disk has different format but is not mounted
  become: true
  ignore_errors: yes

- name: Mount backup disk
  mount:
    path: "{{ backup_dir }}"
    src: /dev/{{ backup_disk_volume }}
    state: mounted
    fstype: ext4
  become: true

- name: Create backup parent dir
  file:
    path: "{{ backup_dir }}/"
    state: directory
    owner: ubuntu
    group: ubuntu
  become: true

- name: Schedule nightly cron job
  cron:
    name: 'Backup geonode data'
    special_time: daily
    job: dir={{ backup_dir }}/day_`date +%d` && mkdir -p $dir && cd $dir && ~/backupRestoreGeonode backup . > backup.out 2> backup.err
    user: ubuntu
  become: true
