---
- name: Install backup shell script
  copy:
    src: backupRestoreGeonode
    dest: ~/backupRestoreGeonode
    mode: 0700

- name: Install shell script to call backup daily
  template:
    src: backupDaily.j2
    dest: ~/backupDaily
    mode: 0700

- name: Test if backup disk mounted
  lineinfile:
    path: /proc/mounts
    regex: '^/dev/{{ backup_disk_volume }}\s{{ backup_dir }}\s/*$'
    state: present
  check_mode: yes
  register: mounts_would_have
  failed_when: (mounts_would_have | changed)
  ignore_errors: yes

- name: Create backup parent dir
  file:
    path: "{{ backup_dir }}"
    state: directory
    owner: ubuntu
    group: ubuntu
  become: true
  when: (mounts_would_have | changed)

- name: create filesystem for backup
  filesystem:
    dev: /dev/{{ backup_disk_volume }}
    fstype: ext4
    # force: yes # Only need this if disk has different format but is not mounted
  become: true
  ignore_errors: yes
  when: (mounts_would_have | changed)

- name: Mount backup disk
  mount:
    path: "{{ backup_dir }}"
    src: /dev/{{ backup_disk_volume }}
    state: mounted
    fstype: ext4
  become: true
  when: (mounts_would_have | changed)

- name: Schedule cron job for just after midnight each weeknight
  cron:
    name: 'Backup geonode data'
    weekday: 2-6
    minute: 15
    hour: 0
    job: ~/backupDaily
    user: ubuntu
  become: true
