---
- name: Install packages
  apt:
    name: '{{ item }}'
    state: installed
    update_cache: yes
  with_items:
   - postgresql
   - postgis
   - postgresql-9.5-postgis-scripts
   - postgresql-contrib
  become: true