---
gnhome: '{{ big_dir }}/geonode'
gsdata: '{{ big_dir }}/geoserver_data'
db_path: '{{ big_dir }}'

old_dbhome: /var/lib/postgresql
postgres_version: 9.5
db_conf_dir: /etc/postgresql/{{ postgres_version }}/main
# dbconf: '{{ db_conf_dir }}/'

geoserver_version: 2.7.4
