---
- name: Install add-apt-repository
  apt:
    name: software-properties-common
    state: latest
  become: true

- name: Add Oracle Java Repository
  apt_repository: repo='ppa:webupd8team/java'
  become: true

- name: Accept Java 8 License
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  become: true

- name: Install Oracle Java 8
  apt:
    name:
      - oracle-java8-installer
      - ca-certificates
      - oracle-java8-set-default
    state: latest
  become: true
