---
- name: Set hostname
  hostname:
    name: "{{ hostname }}"
  become: true

- name: Write hostname into hosts
  lineinfile:
    dest: /etc/hosts
    insertafter: 127.0.0.1 localhost
    line: 127.0.1.1 {{ hostname }}
  become: true
